apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch.fullname" . }}
  labels:
    {{- include "quakewatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    {{- include "quakewatch.selectorLabels" . | nindent 4 }}
