replicaCount: 2

fullnameOverride: quakewatch-app

image:
  repository: liore007/quakewatch
  pullPolicy: IfNotPresent
  tag: "latest"

containerPort: 5000

service:
  type: NodePort
  port: 5000
  nodePort: 30081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 20

envFrom:
  configMap: quakewatch-config
  secret: quakewatch-secret

env: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false

terminationGracePeriodSeconds: 30

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
